version: "3"

services:
  full-perpetuated-container:
    image: ubuntu:22.04
    container_name: ubuntu
    hostname: ubuntu
    restart: always
    ports:
      - "52222:22"
    volumes:
      - ./filesystem/boot:/boot:rw
      - ./filesystem/sys:/sys:rw
      - ./filesystem/etc:/etc:rw
      - ./filesystem/var:/var:rw
      - ./filesystem/usr:/usr:rw
      - ./filesystem/opt:/opt:rw
      - ./filesystem/run:/run:rw
      - ./filesystem/root:/root:rw
      - ./filesystem/home:/home:rw
    command: [ "/usr/bin/supervisord" ]
